<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ajenifer" name="com.training.sanity.tests.RegisterTest" tests="1" failures="1" timestamp="17 Jun 2019 05:15:06 GMT" time="33.659" errors="0">
  <testcase name="RegisterTest" time="33.659" classname="com.training.sanity.tests.RegisterTest">
    <failure type="java.lang.AssertionError" message="expected [Congratulations! Your new account has been successfully created!
You can now take advantage of member privileges to enhance your online shopping experience with us.
If you have ANY questions about the operation of this online shop, please e-mail the store owner.
A confirmation has been sent to the provided e-mail address. If you have not received it within the hour, please contact us.] but found [Congratulations! Your new account has been successfully created!]">
      <![CDATA[java.lang.AssertionError: expected [Congratulations! Your new account has been successfully created!
You can now take advantage of member privileges to enhance your online shopping experience with us.
If you have ANY questions about the operation of this online shop, please e-mail the store owner.
A confirmation has been sent to the provided e-mail address. If you have not received it within the hour, please contact us.] but found [Congratulations! Your new account has been successfully created!]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.training.pom.RegisterPOM.confirm(RegisterPOM.java:103)
	at com.training.sanity.tests.RegisterTest.RegisterTest(RegisterTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- RegisterTest -->
</testsuite> <!-- com.training.sanity.tests.RegisterTest -->
